# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/frame_data.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'src/frame_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14src/frame_data.proto\x12\tframedata\"\x9e\x01\n\x04Tile\x12\x0f\n\x07tile_id\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\r\n\x05width\x18\x04 \x01(\x05\x12\x0e\n\x06height\x18\x05 \x01(\x05\x12\r\n\x05\x63odec\x18\x06 \x01(\t\x12\x12\n\nhas_motion\x18\x07 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x08 \x01(\x0c\x12\x0c\n\x04size\x18\t \x01(\x05\x12\x11\n\ttimestamp\x18\n \x01(\x03\"\x8c\x01\n\x05\x46rame\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x1e\n\x05tiles\x18\x05 \x03(\x0b\x32\x0f.framedata.Tile\x12\x12\n\ntile_count\x18\x06 \x01(\x05\x12\x11\n\ttimestamp\x18\x07 \x01(\x03\"\x82\x01\n\rStreamMessage\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x1f\n\x05\x66rame\x18\x02 \x01(\x0b\x32\x10.framedata.Frame\x12\x16\n\x0estatus_message\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\r\n\x05width\x18\x05 \x01(\x05\x12\x0e\n\x06height\x18\x06 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.frame_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TILE']._serialized_start=36
  _globals['_TILE']._serialized_end=194
  _globals['_FRAME']._serialized_start=197
  _globals['_FRAME']._serialized_end=337
  _globals['_STREAMMESSAGE']._serialized_start=340
  _globals['_STREAMMESSAGE']._serialized_end=470
# @@protoc_insertion_point(module_scope)
